name: zerok
favicon: null
layout_spectrum: 0.75422
typography_spectrum: 0.49916
title: zero degree kelvin
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#414f62'
    - '#667b98'
    - '#00b7ff'
  brandStrength: 0.5
  lightness: 0.917258488945663
  saturation: 0.5
  rhythmicContrast: 0.057618013583123684
purpose: []
