name: zerok
favicon: null
layout_spectrum: 0.25591
typography_spectrum: 0.5
title: zero degree kelvin
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#31292c'
    - '#c78937'
    - '#ffc100'
    - '#c0001f'
  brandStrength: 0.5
  lightness: 0.917258488945663
  saturation: 0.625
  rhythmicContrast: 0.057618013583123684
purpose: []
